# docker-compose.yml
version: '3.8'

services:
  db:
    image: postgres:15
    container_name: whatsapp_clone_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: whatsapp_clone
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
